# ========== 画质设置 ==========
profile=gpu-hq                        # 使用高画质预设
vo=gpu-next                           # 使用新的GPU渲染器
gpu-api=auto                          # 自动选择最佳GPU API
dither-depth=auto                     # 自动抖动深度
hwdec=auto-safe
hwdec-codecs=all

video-sync=display-resample
interpolation
tscale=oversample                     # 使得插值更平滑

 d3d11-adapter      = "AMD Radeon RX 7900 XTX"
#  d3d11-adapter      = "Intel(R) UHD Graphics"
 vulkan-device      = "AMD Radeon RX 7900 XTX"
#  vulkan-device      = "Intel(R) UHD Graphics"
                                   


# ========== 播放控制 ==========
keep-open=always                      # 播放完暂停
save-position-on-quit=yes
watch-later-options-remove=sub-pos    # 避免 ModernZ 动态抬升字幕与断点保存冲突


# ========== 音频/字幕 ==========

audio-file-auto=fuzzy
audio-channels=stereo
audio-normalize-downmix=yes

volume                 = 0       # 播放器启动音量
volume-max             = 200      # 最大音量
sub-auto=fuzzy
alang=ja,en,zh
slang=zh,en,ja

# 字幕样式
# sub-font='Noto Sans CJK SC'
# sub-font-size=48
# sub-color='#FFFFFF'
# sub-border-size=3
# sub-border-color='#000000'
# sub-shadow-offset=1
# sub-shadow-color='#000000'

# 次字幕配置
secondary-sid=auto
secondary-sub-pos=95
secondary-sub-visibility=yes


# ========== 界面设置 ==========
osc=no                                # 禁用默认OSC (使用 ModernZ)
osd-bar=no
border=no
autofit-larger=80%x80%


# Anime4K 默认关闭，可通过 input.conf 中的 Ctrl+1～6 手动启用
